### PR TITLE
Updated images and added figures to the documentation

### PR DESCRIPTION
**Pull request by khenrichsen**

### CODE REVIEW

**Comment by alfmags** [comment]
7->6 days. I believe that is the current limitation. Can you confirm @tht13 ?

**Comment by tht13** [comment]
Yes that is correct

**Comment by khenrichsen** [comment]
Nice catch @alfmags. Changed it to 6 days now :)

**Comment by tht13** [comment]
🚀

**Comment by khenrichsen** [comment]
Just removed 1 min ago @tht13. Sneaked their way in when I made the font bigger in one of the figures. Merge?

**Comment by tht13** [comment]
merged

**Pull request merged**
