### PR TITLE
Document new optional orderId

### PR DESCRIPTION
**Pull request by tht13**

### CODE REVIEW

**Comment by cloveras** [comment]
Can `orderId` be more than 15 characters? UUID is 36 characters, so that may be nice? In the eCom API the max length is 30.

**Comment by tht13** [comment]
we can increase to 30, I just couldn't remember what the ecom limit was so set this cautiously

**Comment by cloveras** [comment]
```
        orderId:
          type: string
          description: >-
            Id which uniquely identifies a payment. Maximum length is 30
            alphanumeric characters: a-z, A-Z, 0-9 and '-'.
          example: order123abc
          pattern: '^[a-zA-Z0-9-]{1,30}$'
          maxLength: 30
```

**Comment by tht13** [comment]
will need to update backend parsing first, but yes 👍 (hyphen is not supported)

**Pull request merged**
