### PR TITLE
Redirect all links to the new website

### PR DESCRIPTION
**Pull request by rebekaburnett**

### CODE REVIEW

**Comment by rebekaburnett** [comment]
Hi guys - I know you're busy and working in the docs, so if you have something in work, we'll just wait and do this later.

**Review by ameliemaucade — APPROVED** [review]

**Comment by ameliemaucade** [comment]
> Hi guys - I know you're busy and working in the docs, so if you have something in work, we'll just wait and do this later.

We can merge it 👍 Don't think the merge conflicts will be too complicated

**Comment by ameliemaucade** [comment]
> Ok, great!! Should we wait for the other guys in case it affects them?

@skasti maybe ? Since there is this PR https://github.com/vippsas/vipps-recurring-api/pull/261 ?

**Comment by rebekaburnett** [comment]
It looks like all the PRs are merged now. I've rebased this PR and it seems safe to merge it now. So I will do that.

**Pull request merged**
