### PR TITLE
New postman v3

### PR DESCRIPTION
**Pull request by rebekaburnett**
This has many things fixed, but there are still most things not working for strange reasons.

### CODE REVIEW

**Comment by rebeksburnett** [comment]
Hi @ameliemaucade !
Here is the v3 postman that you were initially working on before it got merged into the repo. I fixed several things, but I still don't get it to work for the different campaign types, for profile flow, or for any charges when using the v3 path.

**Comment by ameliemaucade** [comment]
Ok thanks @rebeksburnett,  will check it out ! On which test environment are you trying it out ? uat or mt ?

**Comment by rebeksburnett** [comment]
> Ok thanks @rebeksburnett, will check it out ! On which test environment are you trying it out ? uat or mt ?

MT

**Comment by ameliemaucade** [comment]
> > Ok thanks @rebeksburnett, will check it out ! On which test environment are you trying it out ? uat or mt ?
> 
> MT

Might be an issue in MT then. Will look into it

**Comment by ameliemaucade** [comment]
> > > Ok thanks @rebeksburnett, will check it out ! On which test environment are you trying it out ? uat or mt ?
> > 
> > 
> > MT
> 
> Might be an issue in MT then. Will look into it

**Comment by ameliemaucade** [comment]
> Hi @ameliemaucade ! Here is the v3 postman that you were initially working on before it got merged into the repo. I fixed several things, but I still don't get it to work for the different campaign types, for profile flow, or for any charges when using the v3 path.

For now, only price campaigns are enabled in MT but we can enable all the other campaign types if you want to do some tests. 
For the profile flow, the wrong token was used, should be fixed now.

**Comment by rebeksburnett** [comment]
@ameliemaucade That's great!! Thanks for fixing those things!  
If you want, we can keep this PR here until you are ready to release v3. 
You can edit it and merge it when you want. When will v3 be released?

**Comment by ameliemaucade** [comment]
> @ameliemaucade That's great!! Thanks for fixing those things! If you want, we can keep this PR here until you are ready to release v3. You can edit it and merge it when you want. When will v3 be released?

Yes let's to do that 👍 
Don't know when exactly v3 will be released but should be soon, we are waiting for iOS to finish some tasks first.

**Pull request merged**
